branch-defaults:
  development:
    environment: canopy-epm-server-dev
  master:
    environment: canopy-epm-server-test
environment-defaults:
  canopy-epm-server-dev:
    branch: null
    repository: null
global:
  application_name: canopy-epm-server-test
  default_ec2_keyname: venturplex-canopy-poc
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Node.js running on
    64bit Amazon Linux/4.4.0
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
