branch-defaults:
  master:
    environment: canopy-epm-server-test
    group_suffix: null
  development:
    environment: canopy-epm-server-dev
global:
  application_name: canopy-epm-server-test
  branch: null
  default_ec2_keyname: venturplex-canopy-poc
  default_platform: Node.js
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
